version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      # Local path where your home assistant config will be stored
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
    #Le port sur lequel sera accessible l'interface web PORT_EXPORTE:PORT_CONTENEUR
      - 8123:8123
    privileged: true
    depends_on:
      - mariadb # MariaDB is optional (only if you would like to use a different database for HA).
      - zigbee2mqtt  # zigbee2mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).
      - eclipse-mosquitto # aka mosquitto-mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).


  # MariaDb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    volumes:
      # Local path where the database will be stored.
      - ./store/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  # eclipse-mosquitto (MQTT broker)
  eclipse-mosquitto:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

  # zigbee2mqtt
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro 
    devices:
      - "${ZIGBEE_ADAPTER_TTY}"
    privileged: true
    ports:    
      - 8080:8080
    depends_on:
      - eclipse-mosquitto # aka mosquitto-mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).

 # Visual Studio code
  vscode:
   container_name: vscode
   image: codercom/code-server:latest
   restart: always
   environment:
     PASSWORD: "${VSCODE_PASSWORD}"
   volumes:
     - .:/home/coder/project
     - ./store/coder:/home/coder/.local/share/code-server
   ports:
     - 8443:8443
   command: code-server --auth password --port 8443 --disable-telemetry /home/coder/project
