version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      # Local path where your home assistant config will be stored
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - 8123:8123
    privileged: true
    depends_on:
      - mariadb # MariaDB is optional (only if you would like to use a different database for HA).
      - zigbee2mqtt  # zigbee2mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).

  # MariaDb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    volumes:
      # Local path where the database will be stored.
      - ./store/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
    volumes:
    #Bind mount pour la configuration
      - ./config/mosquitto/:/mosquitto/config/
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always

 # Visual Studio code
  vscode:
   container_name: vscode
   image: codercom/code-server:latest
   restart: always
   environment:
     PASSWORD: "${VSCODE_PASSWORD}"
   volumes:
     - .:/home/coder/project
     - ./store/coder:/home/coder/.local/share/code-server
   ports:
     - 8443:8443
   command: code-server --auth password --port 8443 --disable-telemetry /home/coder/project
